name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    # リポジトリをチェックアウトする
    - name: Checkout repository
      uses: actions/checkout@v3

    # Node.js のバージョンをセットアップする
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # パッケージのインストール
    - name: Install dependencies
      run: npm install

    # ビルド
    - name: Run tests using Makefile
      run: make production

